export enum SkillEnum {
  Html5 = "html5",
  CSS3 = "css3",
  SASS = "sass",
  JavaScript = "js",
  TypeScript = "ts",
  JQuery = "jquery",
  React = "react",
  Redux = "redux",
  Angular2 = "angular2",
  Jasmine = "jasmine",
  Webpack = "webpack",
  Grunt = "grunt",
  Gulp = "gulp",
  Node = "node",
  CSharp = "csharp",
  Java = "java",
  MongoDB = "mongodb",
  PostgreSQL = "postgresql",
  GIT = "git",
  NGINX = "nginx",
  VisualStudio = "vs",
  Android = "android",
  Websockets = "websockets",
  Ionic = "ionic",
  Panelleum = "panelleum",
  Processing = "processing",
}
